### ISSUE TITLE
ValueError: could not convert string to float: 'a'

### ISSUE THREAD

**Issue by Tsuasahi** [Meowcolm024/FGO-One#5]
```
[BASIC] Buttons: [1595, 956]
/sdcard/sh.png: 1 file pulled. 26.2 MB/s (2611215 bytes in 0.095s)
ses: []
[0, 2, 4]
ses: [0, 2, 4]
[0, 2, 4]
ana
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    end = s.recognize()
  File "C:\Users\Tsuasahi\Desktop\FGO-One-0.3.0-alpha\interface\Major.py", line 72, in recognize
    self.get_battle()
  File "C:\Users\Tsuasahi\Desktop\FGO-One-0.3.0-alpha\interface\Major.py", line 65, in get_battle
    combat = Battle()
  File "C:\Users\Tsuasahi\Desktop\FGO-One-0.3.0-alpha\cards\Combat.py", line 20, in __init__
    self.card_crd = self.get_np()
  File "C:\Users\Tsuasahi\Desktop\FGO-One-0.3.0-alpha\cards\Combat.py", line 29, in get_np
    if float(a) / float(b) == 1:
ValueError: could not convert string to float: 'a'

```

python3.7.2
Can you help me?

**Comment by Meowcolm024** [comment]
If it happens only a few times, it is fine since haven't written the exception handling(sorry about that). 

This is actually a process of using tesseract to recognize (from line ```if float(a) / float(b) == 1:``` and ```ValueError: could not convert string to float: 'a'``` we could figure out that)the current _turn_ in order to decide whether it is time to release the noble phantasm. However, the background may be complicated and may disturb the recognition. Thus, the recognition may fail and lead to this error.

__So, if it just happens once, you might just ignore it...__

However if it happens constantly, here is the way to fix it:
1. Change _line 29_ in file _Combat.py_ from ```if float(a) / float(b) == 1:``` to ``` if True:```(or just delete the if-else. However, this may lead to the stage where the script would release the noble phantasm whenever it is ready.
2. You can disable the noble phantasm function by just leaving ```return self.get_arrangement()``` in the function ```def get_np(self):``` (I know it is not a good choice)
3. Or alternatively, just add the exception handling (which I don't know how to, since I'm not familiar with Python)

I hope it could solve your problem :)

**Comment by Tsuasahi** [comment]
Thank you. I take the first steps and it works well.
